# Generated by Django 2.1.1 on 2018-10-06 11:33

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20181005_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_text',
            field=tinymce.models.HTMLField(),
        ),
    ]
